default:
  models:
    TrainingQuestion: read
    TrainingContent: read
    TrainingProgram: read
    Facility: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy
    # Add any models all users should be able to read

vendor:
  manageable_roles:
    - vendor
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update
    # Add models that vendors should have access to
    TrainingProgram: read

employee:
  manageable_roles:
    - employee
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update
    # Add models that employees should have access to
    TrainingProgram: read

coordinator:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
    - vendor
    - employee
  manageable_roles:
    - admin
    - editor
    - vendor
    - employee
  models:
    TrainingQuestion: manage
    TrainingContent: manage
    TrainingProgram: manage
    Facility: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
