# Training Program Roles
default:
  models:
    TrainingProgram: show
    TrainingContent: show
    TrainingCertificate: show

employee:
  models:
    TrainingProgram: show
    TrainingContent:
      - show
      - do_training
    TrainingCertificate:
      - show
      - download
    TrainingMembership:
      - show
      - track_progress

vendor:
  includes:
    - employee
  models:
    TrainingProgram:
      - show
      - manage_team_access
    TrainingContent:
      - show
      - do_training
      - manage_team_progress
    TrainingCertificate:
      - show
      - download
      - view_team_certificates
    TrainingMembership:
      - show
      - track_progress
      - manage_team_members

customer:
  manageable_roles:
    - employee
    - vendor
    - customer
  models:
    TrainingProgram: manage_training
    TrainingContent: manage_content
    TrainingCertificate: manage_certificates
    TrainingMembership: manage_memberships
    TrainingQuestion: manage_questions
