name: PDF Generation Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true

    - name: Install required fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-open-sans
        mkdir -p app/assets/fonts
        cp /usr/share/fonts/truetype/open-sans/OpenSans-Regular.ttf app/assets/fonts/
        cp /usr/share/fonts/truetype/open-sans/OpenSans-Bold.ttf app/assets/fonts/

    - name: Run PDF generation tests
      run: |
        bundle exec rails db:setup RAILS_ENV=test
        bundle exec rails test test/jobs/generate_certificate_pdf_job_test.rb

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/myapp_test
      REDIS_URL: redis://localhost:6379/0